using UnityEngine;

namespace Madbox.InputSystem
{
    /// <summary>
    /// Gameplay-facing movement intent generated by an input source.
    /// worldDirection is expected to be on the XZ plane.
    /// </summary>
    public readonly struct MoveIntent
    {
        public Vector3 WorldDirection { get; }
        public float Strength { get; }
        public bool IsMoving { get; }

        public static MoveIntent Idle => new MoveIntent(Vector3.zero, 0f, false);

        public MoveIntent(Vector3 worldDirection, float strength, bool isMoving)
        {
            WorldDirection = worldDirection;
            Strength = Mathf.Clamp01(strength);
            IsMoving = isMoving;
        }
    }
}
